"""hello migration

Revision ID: 7156bf392473
Revises: cbd8cccc361a
Create Date: 2025-01-26 05:53:49.091485

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = '7156bf392473'
down_revision = 'cbd8cccc361a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('hello', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'hello')
    # ### end Alembic commands ###
