"""version 1.0

Revision ID: 807e9a1448d2
Revises: 
Create Date: 2025-01-26 23:06:40.077589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807e9a1448d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
