"""initial tables

Revision ID: d6ef94fd3de4
Revises: b7a658250923
Create Date: 2025-05-12 00:40:42.099657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ef94fd3de4'
down_revision = 'b7a658250923'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('avaliacao_fototipo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cor_pele', sa.Integer(), nullable=False),
    sa.Column('cor_olhos', sa.Integer(), nullable=False),
    sa.Column('cor_cabelo', sa.Integer(), nullable=False),
    sa.Column('quantidade_sardas', sa.Integer(), nullable=False),
    sa.Column('reacao_sol', sa.Integer(), nullable=False),
    sa.Column('bronzeamento', sa.Integer(), nullable=False),
    sa.Column('sensibilidade_solar', sa.Integer(), nullable=False),
    sa.CheckConstraint('bronzeamento IN (0, 2, 4, 6)', name='check_bronzeamento'),
    sa.CheckConstraint('cor_cabelo IN (0, 1, 2, 3, 4)', name='check_cor_cabelo'),
    sa.CheckConstraint('cor_olhos IN (0, 1, 2, 3, 4)', name='check_cor_olhos'),
    sa.CheckConstraint('cor_pele IN (0, 2, 4, 8, 12, 16, 20)', name='check_cor_pele'),
    sa.CheckConstraint('quantidade_sardas IN (0, 1, 2, 3)', name='check_quantidade_sardas'),
    sa.CheckConstraint('reacao_sol IN (0, 2, 4, 6, 8)', name='check_reacao_sol'),
    sa.CheckConstraint('sensibilidade_solar IN (0, 1, 2, 3, 4)', name='check_sensibilidade_solar'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fatoresRiscoProtecao',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exposicao_solar_prolongada', sa.Boolean(), nullable=False),
    sa.Column('frequencia_exposicao_solar', sa.Enum('Diariamente', 'Algumas vezes por semana', 'Ocasionalmente', name='frequencia_exposicao_enum'), nullable=True),
    sa.Column('queimaduras_graves', sa.Boolean(), nullable=False),
    sa.Column('quantidade_queimaduras', sa.Enum('1-2', '3-5', 'Mais de 5', name='quantidade_queimaduras_enum'), nullable=True),
    sa.Column('uso_protetor_solar', sa.Boolean(), nullable=False),
    sa.Column('fator_protecao_solar', sa.Enum('15', '30', '50', '70', '100 ou mais', name='fator_protecao_enum'), nullable=True),
    sa.Column('uso_chapeu_roupa_protecao', sa.Boolean(), nullable=False),
    sa.Column('bronzeamento_artificial', sa.Boolean(), nullable=False),
    sa.Column('checkups_dermatologicos', sa.Boolean(), nullable=False),
    sa.Column('frequencia_checkups', sa.Enum('Anualmente', 'A cada 6 meses', 'Outro', name='frequencia_checkups_enum'), nullable=True),
    sa.Column('frequencia_checkups_outro', sa.String(length=100), nullable=True),
    sa.Column('participacao_campanhas_prevencao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historicoCancerPele',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('historico_familiar', sa.Boolean(), nullable=False),
    sa.Column('grau_parentesco', sa.Enum('Pai', 'Mãe', 'Avô/Avó', 'Irmão/Irmã', 'Outro', name='grau_parentesco_enum'), nullable=True),
    sa.Column('tipo_cancer_familiar', sa.Enum('Melanoma', 'Carcinoma Basocelular', 'Carcinoma Espinocelular', 'Outro', name='tipo_cancer_familiar_enum'), nullable=True),
    sa.Column('tipo_cancer_familiar_outro', sa.String(length=100), nullable=True),
    sa.Column('diagnostico_pessoal', sa.Boolean(), nullable=False),
    sa.Column('tipo_cancer_pessoal', sa.Enum('Melanoma', 'Carcinoma Basocelular', 'Carcinoma Espinocelular', 'Outro', name='tipo_cancer_pessoal_enum'), nullable=True),
    sa.Column('tipo_cancer_pessoal_outro', sa.String(length=100), nullable=True),
    sa.Column('lesoes_precancerigenas', sa.Boolean(), nullable=False),
    sa.Column('tratamento_lesoes', sa.Boolean(), nullable=False),
    sa.Column('tipo_tratamento', sa.Enum('Cirurgia', 'Crioterapia', 'Radioterapia', 'Outro', name='tipo_tratamento_enum'), nullable=True),
    sa.Column('tipo_tratamento_outro', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigacaoLesoesSuspeitas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mudanca_pintas_manchas', sa.Boolean(), nullable=False),
    sa.Column('sintomas_lesoes', sa.Boolean(), nullable=False),
    sa.Column('tempo_alteracoes', sa.Enum('Menos de 1 mês', '1-3 meses', '3-6 meses', 'Mais de 6 meses', name='tempo_alteracoes_enum'), nullable=True),
    sa.Column('caracteristicas_lesoes', sa.Boolean(), nullable=False),
    sa.Column('consulta_medica', sa.Boolean(), nullable=False),
    sa.Column('diagnostico_lesoes', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locais_lesao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_locais_lesao_id'), 'locais_lesao', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nivel_acesso', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('saudeGeral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doencas_cronicas', sa.Boolean(), nullable=False),
    sa.Column('hipertenso', sa.Boolean(), nullable=False),
    sa.Column('diabetes', sa.Boolean(), nullable=False),
    sa.Column('cardiopatia', sa.Boolean(), nullable=False),
    sa.Column('outras_doencas', sa.String(length=300), nullable=True),
    sa.Column('diagnostico_cancer', sa.Boolean(), nullable=False),
    sa.Column('tipo_cancer', sa.String(length=100), nullable=True),
    sa.Column('uso_medicamentos', sa.Boolean(), nullable=False),
    sa.Column('medicamentos', sa.String(length=500), nullable=True),
    sa.Column('possui_alergia', sa.Boolean(), nullable=False),
    sa.Column('alergias', sa.String(length=500), nullable=True),
    sa.Column('ciruturgias_dermatologicas', sa.Boolean(), nullable=False),
    sa.Column('tipo_procedimento', sa.String(length=200), nullable=True),
    sa.Column('pratica_atividade_fisica', sa.Boolean(), nullable=False),
    sa.Column('frequencia_atividade_fisica', sa.Enum('Diária', 'Frequente', 'Moderada', 'Ocasional', name='frequencia_atividade_fisica_enum'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saudeGeral_id'), 'saudeGeral', ['id'], unique=False)
    op.create_table('termoConsentimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('data_acordo', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_termoConsentimento_id'), 'termoConsentimento', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_usuario', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True),
    sa.Column('password_reset_token_used', sa.Boolean(), nullable=True),
    sa.Column('email_invite_token', sa.String(length=255), nullable=True),
    sa.Column('email_invite_token_used', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario_criacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario_atualizacao', sa.Integer(), nullable=True),
    sa.Column('fl_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_atualizacao'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criacao'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cpf'), 'users', ['cpf'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_nome_usuario'), 'users', ['nome_usuario'], unique=False)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_paciente', sa.String(length=100), nullable=False),
    sa.Column('data_nascimento', sa.DATE(), nullable=False),
    sa.Column('sexo', sa.Enum('M', 'F', 'NB', 'NR', 'O', name='sexo_enum'), nullable=False),
    sa.Column('sexo_outro', sa.String(length=100), nullable=True),
    sa.Column('cpf_paciente', sa.String(length=11), nullable=False),
    sa.Column('num_cartao_sus', sa.String(length=15), nullable=False),
    sa.Column('endereco_paciente', sa.String(length=300), nullable=False),
    sa.Column('telefone_paciente', sa.String(length=11), nullable=False),
    sa.Column('email_paciente', sa.String(length=100), nullable=False),
    sa.Column('autoriza_pesquisa', sa.Boolean(), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario_criacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario_atualizacao', sa.Integer(), nullable=True),
    sa.Column('fl_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_atualizacao'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criacao'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf_paciente'), 'pacientes', ['cpf_paciente'], unique=True)
    op.create_index(op.f('ix_pacientes_id'), 'pacientes', ['id'], unique=False)
    op.create_index(op.f('ix_pacientes_num_cartao_sus'), 'pacientes', ['num_cartao_sus'], unique=True)
    op.create_table('unidadeSaude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_unidade_saude', sa.String(length=100), nullable=False),
    sa.Column('nome_localizacao', sa.String(length=300), nullable=False),
    sa.Column('codigo_unidade_saude', sa.String(length=50), nullable=False),
    sa.Column('cidade_unidade_saude', sa.String(length=100), nullable=False),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario_criacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario_atualizacao', sa.Integer(), nullable=True),
    sa.Column('fl_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuario_atualizacao'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criacao'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unidadeSaude_codigo_unidade_saude'), 'unidadeSaude', ['codigo_unidade_saude'], unique=True)
    op.create_index(op.f('ix_unidadeSaude_id'), 'unidadeSaude', ['id'], unique=False)
    op.create_index(op.f('ix_unidadeSaude_nome_unidade_saude'), 'unidadeSaude', ['nome_unidade_saude'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_atendimento', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('termo_consentimento_id', sa.Integer(), nullable=True),
    sa.Column('saude_geral_id', sa.Integer(), nullable=True),
    sa.Column('avaliacao_fototipo_id', sa.Integer(), nullable=True),
    sa.Column('historico_cancer_pele_id', sa.Integer(), nullable=True),
    sa.Column('fatores_risco_protecao_id', sa.Integer(), nullable=True),
    sa.Column('investigacao_lesoes_suspeitas_id', sa.Integer(), nullable=True),
    sa.Column('unidade_saude_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_atualizacao', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id_usuario_criacao', sa.Integer(), nullable=True),
    sa.Column('id_usuario_atualizacao', sa.Integer(), nullable=True),
    sa.Column('fl_ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['avaliacao_fototipo_id'], ['avaliacao_fototipo.id'], ),
    sa.ForeignKeyConstraint(['fatores_risco_protecao_id'], ['fatoresRiscoProtecao.id'], ),
    sa.ForeignKeyConstraint(['historico_cancer_pele_id'], ['historicoCancerPele.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_atualizacao'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_usuario_criacao'], ['users.id'], ),
    sa.ForeignKeyConstraint(['investigacao_lesoes_suspeitas_id'], ['investigacaoLesoesSuspeitas.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['saude_geral_id'], ['saudeGeral.id'], ),
    sa.ForeignKeyConstraint(['termo_consentimento_id'], ['termoConsentimento.id'], ),
    sa.ForeignKeyConstraint(['unidade_saude_id'], ['unidadeSaude.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_table('user_unidadeSaude',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unidadeSaude_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unidadeSaude_id'], ['unidadeSaude.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    op.create_table('registroLesoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_lesao_id', sa.Integer(), nullable=False),
    sa.Column('descricao_lesao', sa.String(length=500), nullable=False),
    sa.Column('atendimento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimentos.id'], ),
    sa.ForeignKeyConstraint(['local_lesao_id'], ['locais_lesao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registroLesoes_id'), 'registroLesoes', ['id'], unique=False)
    op.create_table('registroLesoesImagens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arquivo_path', sa.String(length=300), nullable=False),
    sa.Column('registro_lesoes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['registro_lesoes_id'], ['registroLesoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registroLesoesImagens_id'), 'registroLesoesImagens', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registroLesoesImagens_id'), table_name='registroLesoesImagens')
    op.drop_table('registroLesoesImagens')
    op.drop_index(op.f('ix_registroLesoes_id'), table_name='registroLesoes')
    op.drop_table('registroLesoes')
    op.drop_table('user_unidadeSaude')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_unidadeSaude_nome_unidade_saude'), table_name='unidadeSaude')
    op.drop_index(op.f('ix_unidadeSaude_id'), table_name='unidadeSaude')
    op.drop_index(op.f('ix_unidadeSaude_codigo_unidade_saude'), table_name='unidadeSaude')
    op.drop_table('unidadeSaude')
    op.drop_index(op.f('ix_pacientes_num_cartao_sus'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_id'), table_name='pacientes')
    op.drop_index(op.f('ix_pacientes_cpf_paciente'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_users_nome_usuario'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cpf'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_termoConsentimento_id'), table_name='termoConsentimento')
    op.drop_table('termoConsentimento')
    op.drop_index(op.f('ix_saudeGeral_id'), table_name='saudeGeral')
    op.drop_table('saudeGeral')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locais_lesao_id'), table_name='locais_lesao')
    op.drop_table('locais_lesao')
    op.drop_table('investigacaoLesoesSuspeitas')
    op.drop_table('historicoCancerPele')
    op.drop_table('fatoresRiscoProtecao')
    op.drop_table('avaliacao_fototipo')
    # ### end Alembic commands ###
