"""hello migration

Revision ID: e7c3de348df4
Revises: 7156bf392473
Create Date: 2025-01-26 06:07:01.934027

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel             # NEW


# revision identifiers, used by Alembic.
revision = 'e7c3de348df4'
down_revision = '7156bf392473'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('song', 'hello')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('song', sa.Column('hello', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
